# Generated by Django 4.2.9 on 2024-02-07 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('state', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('confirmation_code', models.CharField(max_length=50)),
                ('confirmation_url', models.URLField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
