# Generated by Django 4.2.9 on 2024-04-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
    ]
