# Generated by Django 4.2.9 on 2024-03-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.BinaryField(null=True),
        ),
    ]
