# Generated by Django 4.2.9 on 2024-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='has_default_password',
            field=models.BooleanField(default=False),
        ),
    ]
