# Generated by Django 4.2.9 on 2024-03-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
