# Generated by Django 4.2.9 on 2024-03-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_users_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user/user_pictures/'),
        ),
    ]
