# Generated by Django 4.2.9 on 2024-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='applications/user/user_pictures/'),
        ),
    ]
