# Generated by Django 4.2.9 on 2024-03-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_users_is_active_alter_users_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
