# Generated by Django 4.2.9 on 2024-03-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code_verification',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
