# Generated by Django 4.2.9 on 2024-03-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='has_set_attention_times',
            field=models.BooleanField(default=False),
        ),
    ]
