# Generated by Django 4.2.9 on 2024-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aditional_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditionalinformation',
            name='icon',
            field=models.TextField(),
        ),
    ]
