# Generated by Django 4.2.9 on 2024-04-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aditional_information', '0002_alter_aditionalinformation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditionalinformation',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
